# H2 Console Setting
spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        globally_quoted_identifiers: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true